name: Remaken CI
run-name: ${{ github.actor }} - run Remaken CI
on: [push]
jobs:
  windows-ci:
    runs-on: windows-2022
    steps:
      # Remaken git checkout
      - name: Remaken git checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Pkgconfig
      - name: Pkgconfig
        run: choco install -yr --acceptlicense --no-progress --allow-empty-checksums pkgconfiglite

      # Visual Studio 2019 Community
      - name: Visual Studio 2019
        run: choco install --allow-empty-checksums visualstudio2019community
      - name: Visual C++ 2019
        run: choco install visualstudio2019-workload-nativedesktop
      #- working-directory: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'
      #  run: .\vswhere.exe
      #- working-directory: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'
      #  run: .\vswhere.exe -requires Microsoft.Component.MSBuild -property installationPath

      # Conan
      - name: Install conan 1.59.0
        run: pip install --upgrade conan==1.59.0
      #- run: echo "C:\Program Files\Conan\conan" | Out-File -Append -FilePath $Env:GITHUB_PATH -Encoding utf8
      # - run: conan --version

      # Conan configuration
      - name: conan profile configuration
        run: |
         conan profile new default --detect
         conan profile update settings.compiler.cppstd=17 default
         conan profile update settings.compiler.version=16 default
         conan profile update settings.compiler.toolset=v142 default

      - name: conan remote
        run: conan remote add -i 0 gitlab_remaken_deps https://gitlab.com/api/v4/projects/53589240/packages/conan
      
      # Install Qt
      - name: Install aqt
        run: choco install aqt
      - name: Install Qt kit 5.15.2 msvc2019 64b
        run: aqt install-qt windows desktop 5.15.2 win64_msvc2019_64 -O ${{ github.workspace }}/tools/Qt
      - name: Install QtCreator
        run: aqt install-tool windows desktop tools_qtcreator -O ${{ github.workspace }}/tools/Qt
      #- run: echo "${{ github.workspace }}/tools/Qt/Tools/QtCreator/bin/jom" | Out-File -Append -FilePath $Env:GITHUB_PATH -Encoding utf8
      #- run: echo "${{ github.workspace }}/tools/Qt/5.15.2/msvc2019_64/bin" | Out-File -Append -FilePath $Env:GITHUB_PATH -Encoding utf8

      # Build solution
      #- run: dir "${{ github.workspace }}\tools\Qt\Tools\qtcreator\bin\jom"
      - name: Build remaken
        working-directory: ./scripts/win
        run: .\build_remaken_project.bat remaken shared ..\.. 5.15.2 "${{ github.workspace }}\tools\Qt\5.15.2\msvc2019_64\bin" "${{ github.workspace }}\tools\Qt\Tools\qtcreator\bin\jom"

  linux-ci:
    runs-on: ubuntu-22.04
    steps:
      # Remaken git checkout
      - name: Remaken git checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # Pkgconfig
      - name: Pkgconfig
        run: pip install pkgconfig
      
      # Install Qt
      - name: Install Qt
        run: sudo apt-get install qtbase5-dev
      
      # Conan
      - name: Conan
        run: pip install --upgrade conan==1.59.0
      
      # Conan configuration
      - name: conan profile configuration
        run: |
         conan profile new default --detect
         conan profile update settings.compiler.libcxx=libstdc++11 default
         conan profile update settings.compiler.cppstd=17 default
         conan profile update settings.compiler.version=11 default
      
      # Build solution
      - name: Build remaken
        working-directory: ./scripts/unixes
        run: ./build_remaken_project.sh remaken shared ../.. 5.15.2 /usr/bin
